# Generated by Django 2.2.5 on 2019-09-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190913_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='username',
            new_name='last_name',
        ),
    ]
